-- UFC 329 event maintenance moved to:
--   supabase/picks-live-gameplay-phase.sql
--
-- Run that migration instead. It contains the canonical 14-fight card,
-- odds snapshot, current results, Underdog Lock support, and live reveal functions.
-- This compatibility file intentionally has no executable statements.
